[[pages]]
path = "pages/about.py"
name = "Ğ Ğ½Ğ°Ñ"
icon = "ğŸ“"

[[pages]]
name = "ĞĞ¾Ğ²Ğ¾ÑÑ‚Ğ¸"
icon = "ğŸ“°"
is_section = true

[[pages]]
path = "pages/news/StartServer.py"
name = "Ğ¡Ñ‚Ğ°Ñ€Ñ‚ ÑĞµÑ€Ğ²ĞµÑ€Ğ°"
icon = "ğŸš€"

[[pages]]
name = "ĞŸÑ€Ğ¾ÑˆĞ»Ñ‹Ğµ Ğ¿Ñ€Ğ¾ĞµĞºÑ‚Ñ‹"
icon = "ğŸ“š"
is_section = true

[[pages]]
path = "pages/pastProjects/StihiyniyPoryadok.py"
name = "Ğ¡Ñ‚Ğ¸Ñ…Ğ¸Ğ¹Ğ½Ñ‹Ğ¹ Ğ¿Ğ¾Ñ€ÑĞ´Ğ¾Ğº"
icon = "ğŸ”®"