[[pages]]
path = "pages/about.py"
name = "Ğ Ğ½Ğ°Ñ"
icon = "ğŸ“"

[[pages]]
name = "ĞŸÑ€Ğ¾ÑˆĞ»Ñ‹Ğµ Ğ¿Ñ€Ğ¾ĞµĞºÑ‚Ñ‹"
icon = "ğŸ“š"
is_section = true

[[pages]]
path = "pages/pastProjects/StihiyniyPoryadok.py"
name = "Ğ¡Ñ‚Ğ¸Ñ…Ğ¸Ğ¹Ğ½Ñ‹Ğ¹ Ğ¿Ğ¾Ñ€ÑĞ´Ğ¾Ğº"
icon = "ğŸ”®"